### ISSUE TITLE
Add attachments

### ISSUE THREAD

**Issue by donhenryiii** [rickh94/attaskcreator#3]
I'd like to add attachments and put them in the records database.

**Comment by rickh94** [comment]
TODO
- [ ] Add config option for Records table, fields (called files internally)
- [ ] Control flow: only execute if attachment present
- [ ] Pull attachments off of emails if present
- [ ] Create new record in files table
- [ ] Upload file to private s3 bucket with short lifecycle, generate pre-signed url
- [ ] Give url to Airtable to download.
- [ ] Get record id and link to task
